pools:
  - gun:
      type: connect
      target: localhost:3000
      ssl: true
      connect-ssl: false
    ammo:
      type: jsonline
      file: ./example/data/ammo.jsonline
    result:
      type: log/phout
      destination: ./http_phout.log
    shared-limits: true
    user-limiter:
      type: periodic
      batch: 2
      max: 3
      period: 1s
    startup-limiter:
      type: periodic
      batch: 1
      max: 5
      period: 0.5s
