pools:
  - id: example
    gun:
      type: example
    ammo:
      type: example
      limit: 100
    result:
      type: log
    rps-schedule:
      type: periodic
      batch: 2
      max: 3
      period: 1s
    startup-schedule:
      type: periodic
      batch: 1
      max: 5
      period: 0.5s
